server:
  port: 9002
management:
  endpoints:
    web:
      base-path: "/macys-order-monitor"
      exposure:
        include: "info"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/macys-order
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

        
  